import time
import config
from db import SessionLocal, Inventory, Target, Prospect, Message, init_db
from platforms.craigslist import CraigslistPlatform
from ai.gemini import evaluate_trade, generate_outreach_message
from protocols.ap2 import create_barter_intent
from notifier import notify_trade_evaluation, notify_message_sent

def run_agent_loop():
    print("=== Starting Autonomous Trading Agent Run ===")

    session = SessionLocal()

    # 1. Load Context
    current_item = session.query(Inventory).filter_by(active=True).first()
    target_item = session.query(Target).first()

    if not current_item or not target_item:
        print("Missing inventory or target in database. Cannot run.")
        session.close()
        return

    print(f"Current Inventory: {current_item.name}")
    print(f"Target Goal: {target_item.name}")

    # Generate an AP2 Intent Mandate to authorize the agent's actions for this run
    intent = create_barter_intent(current_item.name, target_item.name)
    intent_signature = intent.sign()
    print(f"Generated AP2 Intent Mandate [{intent.id}] (Sig: {intent_signature[:10]}...)")

    # 2. Scrape Prospects
    # Search for items slightly more valuable or highly liquid
    # In a fully fleshed out system, the search query itself would be generated by the LLM
    search_queries = ["iphone", "macbook", "ipad", "camera", "ebike", "scooter", "nintendo switch"]

    platform = CraigslistPlatform(region="sfbay")
    new_prospects = []

    for query in search_queries[:2]: # Keep it short for the cron job run
        scraped_products = platform.search_items(query, limit=2)
        for prod in scraped_products:
            # Check if we've seen this before
            exists = session.query(Prospect).filter_by(external_id=prod.id).first()
            if not exists:
                prospect = Prospect(
                    platform="craigslist",
                    external_id=prod.id,
                    title=prod.title,
                    price=prod.price,
                    url=prod.url
                )
                session.add(prospect)
                new_prospects.append((prospect, prod))

    session.commit()
    print(f"Found {len(new_prospects)} new prospects to evaluate.")

    # 3. Evaluate Prospects via Gemini Brain
    for prospect_db, prospect_ucp in new_prospects:
        print(f"\nEvaluating: {prospect_db.title} ({prospect_db.price})")
        eval_result = evaluate_trade(current_item.name, prospect_ucp, target_item.name)

        prospect_db.evaluated = True
        prospect_db.worth_trading = eval_result.get("worth_trading", False)
        prospect_db.evaluation_reason = eval_result.get("reasoning", "No reasoning provided.")
        session.commit()

        # Send Email Notification of Evaluation
        notify_trade_evaluation(prospect_db, prospect_db.evaluation_reason, prospect_db.worth_trading)

        # 4. Message Prospects if Worth Trading
        if prospect_db.worth_trading:
            print("Decided to pursue trade. Generating message...")
            outreach_msg = generate_outreach_message(current_item.name, prospect_ucp)

            # Send message via platform (or dry run)
            success = platform.send_message(prospect_db.url, outreach_msg, dry_run=config.DRY_RUN)

            if success:
                # Log AP2 Cart Mandate generation step conceptually
                print(f"AP2: Agent initiated outreach under Intent {intent.id}")

                prospect_db.contacted = True
                msg_record = Message(
                    prospect_id=prospect_db.id,
                    direction="outbound",
                    content=outreach_msg,
                    is_dry_run=config.DRY_RUN
                )
                session.add(msg_record)
                session.commit()

                notify_message_sent(prospect_db, msg_record, config.DRY_RUN)

            # Rate limiting / polite behavior
            time.sleep(2)

    print("\n=== Agent Run Complete ===")
    session.close()

if __name__ == "__main__":
    # Ensure DB is initialized before first run
    init_db()
    try:
        run_agent_loop()
    except Exception as e:
        print(f"Agent loop encountered an error: {e}")
